swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.ab.testutil.v1.testutil_core-1.0
x-gw-schema-import:
  testutil: gw.content.ab.testutil.v1.testutil_content-1.0
paths: {}