swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.content.ab.admin.v1.admin_content-1.0
x-gw-schema-import:
  admin: ext.admin.v1.admin_ext-1.0
x-gw-apihandlers:
- gw.rest.ext.ab.admin.v1.AdminApiExtHandler
paths: {}