resources:
  BatchProcess:
    resource: gw.rest.core.ab.systemtools.v1.batch.BatchProcessCoreResource
  BatchProcesses:
    resource: gw.rest.core.ab.systemtools.v1.batch.BatchProcessesCoreResource
    defaultSort:
    - type
  DatabaseConsistencyCheck:
    resource: gw.rest.core.ab.systemtools.v1.dbcc.DatabaseConsistencyCheckCoreResource
  DatabaseConsistencyCheckReport:
    resource: gw.rest.core.ab.systemtools.v1.dbcc.DatabaseConsistencyCheckReportCoreResource
  DatabaseConsistencyChecks:
    resource: gw.rest.core.ab.systemtools.v1.dbcc.DatabaseConsistencyChecksCoreResource
    defaultSort:
    - "-startTime"
  SystemToolsOpenApiSchema:
    resource: gw.api.modules.rest.framework.v1.openapi.v3.OpenApiJsonPlatformResource
basePaths:
  systemtools: /systemtools/v1
mappingFiles:
- gw.core.ab.systemtools.v1.systemtools_core-1.0
updaterFiles:
- gw.core.ab.systemtools.v1.systemtools_core-1.0
resourceAccess:
  default:
    yaml: gw.core.ab.systemtools.v1.default_core-1.0
  internal:
    yaml: gw.core.ab.systemtools.v1.internal_core-1.0
  service:
    yaml: gw.core.ab.systemtools.v1.service_core-1.0
  unauthenticated:
    yaml: gw.core.ab.systemtools.v1.unauthenticatedUser_core-1.0