swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.pl.admin.v1.admin_pl-1.0
- gw.core.ab.framework.v1.framework_core-1.0
x-gw-schema-import:
  admin: gw.core.ab.admin.v1.admin_core-1.0
paths: {}
x-gw-cors-policy: admin