swagger: "2.0"
x-gw-cors-policies:
  admin:
    enabled: "${cors.admin.enabled:true}"
    allowOrigins: "${cors.admin.allowOrigins:any}"
    allowCredentials: "${cors.admin.allowCredentials:true}"
    allowHeaders: "${cors.admin.allowHeaders:null}"
    exposeHeaders: "${cors.admin.exposeHeaders:null}"
    maxAge: "${cors.admin.maxAge:1200}"
    allowMethods: "${cors.admin.allowMethods:null}"
  async:
    enabled: "${cors.async.enabled:true}"
    allowOrigins: "${cors.async.allowOrigins:any}"
    allowCredentials: "${cors.async.allowCredentials:true}"
    allowHeaders: "${cors.async.allowHeaders:null}"
    exposeHeaders: "${cors.async.exposeHeaders:null}"
    maxAge: "${cors.async.maxAge:1200}"
    allowMethods: "${cors.async.allowMethods:null}"
  common:
    enabled: "${cors.common.enabled:true}"
    allowOrigins: "${cors.common.allowOrigins:any}"
    allowCredentials: "${cors.common.allowCredentials:true}"
    allowHeaders: "${cors.common.allowHeaders:null}"
    exposeHeaders: "${cors.common.exposeHeaders:null}"
    maxAge: "${cors.common.maxAge:1200}"
    allowMethods: "${cors.common.allowMethods:null}"
  composite:
    enabled: "${cors.composite.enabled:true}"
    allowOrigins: "${cors.composite.allowOrigins:any}"
    allowCredentials: "${cors.composite.allowCredentials:true}"
    allowHeaders: "${cors.composite.allowHeaders:null}"
    exposeHeaders: "${cors.composite.exposeHeaders:null}"
    maxAge: "${cors.composite.maxAge:1200}"
    allowMethods: "${cors.composite.allowMethods:null}"
  contact:
    enabled: "${cors.contact.enabled:true}"
    allowOrigins: "${cors.contact.allowOrigins:any}"
    allowCredentials: "${cors.contact.allowCredentials:true}"
    allowHeaders: "${cors.contact.allowHeaders:null}"
    exposeHeaders: "${cors.contact.exposeHeaders:null}"
    maxAge: "${cors.contact.maxAge:1200}"
    allowMethods: "${cors.contact.allowMethods:null}"
  systemtools:
    enabled: "${cors.systemtools.enabled:true}"
    allowOrigins: "${cors.systemtools.allowOrigins:any}"
    allowCredentials: "${cors.systemtools.allowCredentials:true}"
    allowHeaders: "${cors.systemtools.allowHeaders:null}"
    exposeHeaders: "${cors.systemtools.exposeHeaders:null}"
    maxAge: "${cors.systemtools.maxAge:1200}"
    allowMethods: "${cors.systemtools.allowMethods:null}"