swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.ab.contact.v1.contact_core-1.0
x-gw-schema-import:
  contact: gw.content.ab.contact.v1.contact_content-1.0
paths: {}